version: 2
updates:
  - package-ecosystem: "github_actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    groups:
      terraform:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "terraform"