skip-check:
    - CKV_AWS_157   # Ensure that RDS instances have Multi-AZ enabled
    - CKV_AWS_354   # Ensure RDS Performance Insights are encrypted using KMS CMKs
    - CKV_AWS_103   # Ensure that load balancer is using at least TLS 1.2
    - CKV_AWS_337   # Ensure SSM parameters are using KMS CMK
    - CKV_AWS_179   # Ensure FSX Windows filesystem is encrypted by KMS using a customer managed Key (CMK)
    - CKV2_AWS_57   # Ensure Secrets Manager secrets should have automatic rotation enabled
    - CKV_AWS_149   # Ensure that Secrets Manager secrets are encrypted with KMS CMK