skip-check:
    - CKV_AWS_18    # Ensure the S3 bucket has access logging enabled
    - CKV_AWS_144   # Ensure that S3 bucket has cross-region replication enabled
    - CKV_AWS_145   # Ensure that S3 buckets are encrypted with KMS by default
    - CKV_AWS_157   # Ensure that RDS instances have Multi-AZ enabled
    - CKV_AWS_354   # Ensure RDS Performance Insights are encrypted using KMS CMKs
    - CKV_AWS_378   # Ensure AWS Load Balancer doesn't use HTTP protocol
    - CKV2_AWS_6    # Ensure that S3 bucket has a Public Access block
    - CKV2_AWS_61   # Ensure that an S3 bucket has a lifecycle configuration
    - CKV2_AWS_62   # Ensure S3 buckets should have event notifications enabled
    - CKV2_AWS_62   # Ensure S3 buckets should have event notifications enabled
    - CKV_AWS_2     # Ensure ALB protocol is HTTPS
    - CKV_AWS_103   # Ensure that load balancer is using at least TLS 1.2